"use client";
import Footer from "@/components/footer";
import Header from "@/components/header";
import AppContext from "./context/context";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "aos/dist/aos.css";
import AOS from "aos";
import React, { Suspense, useEffect, useState } from "react";
import Preloader from "@/components/preloader";
import Footernav from "@/components/footernav";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { usePathname } from "next/navigation";
const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Expert Business",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    AOS.init();
  }, []);   
   const pathname = usePathname();

  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setLoading(false);
  }, []);

  const [admin, setAdmin] = useState(false);
  useEffect(() => {

    if (pathname.startsWith("/admin-dashboard")) {
      setAdmin(true);
    }
  }, [pathname]);
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppContext>
          {loading ? (
            <div className="flex justify-center items-center h-screen">
              <Preloader h={"h-28"} w={"w-28"} />
            </div>
          ) : admin ? (
            <>    {children}</>
          ) : (
            <>
              <Suspense>
                <Header />
                {children}
                <Footer />
                <div className="sm:hidden">
                  <Footernav />
                </div>
              </Suspense>
            </>
          )}
        </AppContext>
      </body>
    </html>
  );
}
